ARG version 
FROM almalinux:${version:-9} 
ENV course="devops" \ 
    duration="120hrs" 
ARG trainer="subbu" 
RUN echo "Hi course is ${course},duration is ${duartion},trainer is ${trainer}" 
CMD ["sleep","1000"]    